### ISSUE TITLE
I have a question on AppWrite.

### ISSUE THREAD

**Issue by chamui9** [itsnaveenk/face-recognition-mern-app#1]
Is AppWrite necessary for this project? If not, how do I remove it?

**Comment by replyre** [comment]
Are you talking about face-api.js or the storage of the images for processing?

**Comment by chamui9** [comment]
the storage of the images for processing, but I didn't know that face-api.js was necessary too.

**Comment by replyre** [comment]
@chamui9  For storage, you can use local storage as well if you wish to store data, we used AppWrite as we had to make it work on multiple nodes, You can also use Cloudinary as well. 

face-api.js is the base of this project, You can go to its docs for more information regarding the same.
